# (PART) Data Visualisation {-}

# htmlwidgets {-}

In this chapter we cover the integration of JavaScript with R using the htmlwidgets package, which focuses on libraries that produce a visual output. It is primarily used for data visualisation but is not limited to it.

As in previous chapters we mainly learn by example and build multiple widgets. We first go through some basic principles that must be understood before we actually start writing code, we then write a simple widget that allows animating text, then move on to others to progressively include more data and features, finally we build up on the previous chapter to improve how htmlwidgets work with shiny.

## How it works~ish {-}

Imagine there is no such package as htmlwidgets to help create interactive visualisations from R: how would one attempt to go about it?

An interactive visualisation using JavaScript will require an html document, therefore it would probably have to be created first. Secondly, the visualisation that is yet to be created likely relies on external libraries, these would need to be imported in the document. The document should also include an html element (e.g.: `<div>`) to host said visualisation. Then data would have to be serialised in R and embedded into the document where it should be read by JavaScript code that uses it to create the visualisation. Finally all should be managed to work seamlessly across R markdown, shiny, and other settings.

Thankfully the htmlwidgets package is there to handle most of this. Nonetheless, it is important to understand that these operations are undertaken (to so degree) by htmlwidgets as it greatly helps use the package.

Must remember when using htmlwidgets:

- Import dependencies
- Create an html element to hold visualisation
- Serialise R data to JSON
- Handle JSON data to produce visualisation

## Scaffold & Explore

With some understanding, albeit limited, of how htmlwidgets work one is ready to "scaffold" a widget and explore how it works.
