# Custom Outputs

In this chapter we create a custom shiny output, in practical terms this creates custom `render*` and `*Output` functions to use in Shiny. This will be demonstrated by creating something akin to the `valueBox` available in the shinydashboard [@R-shinydashboard] package. While similar to what shinydashboard provides this box will 1) be fully customisable and 2) available in any shiny application. 

## Inner-workings 

At the core, this consists in creating three functions; `boxxy`, `renderBoxxy` and `boxxyOutput` (analogous to `plot`, `renderPlot`, `plotOutput`) which are linked by an "output binding" in JavaScript. 

The first function, `boxxy` will accept arguments that help define what is in the box.

The latter function essentially creates an HTML element (e.g.: `<div>`) with its dependencies attached, the former `render*` rather straightforward, unlike previous examples, the data does not need to be explicitly sent to the front-end using `session$sendCustomMessage` as this is handled by shiny itself under the hood.

Previous work with shiny and JavaScript covered in this book had no dedicated "output" element that were placed in the shiny UI, therefore one had to use a function solely dedicated to importing the dependencies (e.g.: `usejBox`). However, since this is not the case here the dependencies can be attached together with the output.

Finally, the two R functions are "bound" JavaScript-side with an "output binding" that renders the data from the `render*` function with its `*output`.
